services:
  app1:
    build: .
    container_name: fastapi-server1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8001:8000
    volumes:
      - .:/code
    depends_on:
      - redis

  app2:
    build: .
    container_name: fastapi-server2
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8002:8000
    volumes:
      - .:/code
    depends_on:
      - redis    

  redis:
    image: redis:alpine
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
